name: Docker Image CI

on:
  push:
    branches:
      - 'docker'    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag conman-CI:$(date +%s)
